import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

/**
 * Reports Service
 * 
 * NOTE: The Reporting Service is implemented as an AWS Lambda function that is triggered
 * by ExperimentCompleted events. Reports are NOT managed via REST API.
 * 
 * Reports are generated asynchronously and stored in S3. Access to reports should be
 * obtained through the experiment context (e.g., via Dashboard's getExperimentFull endpoint).
 * 
 * This service is a stub for future implementation of S3-based report retrieval.
 * 
 * Architecture:
 * - ExperimentCompleted event → EventBridge → Lambda (Report Generator)
 * - Lambda generates report → stores in S3 → emits ReportGenerated event
 * - Frontend retrieves report metadata via experiment details
 * - Frontend downloads report directly from S3 presigned URL
 */
@Injectable({
  providedIn: 'root'
})
export class ReportsService {
  
  constructor() {}
  
  /**
   * TODO: Implement S3-based report retrieval
   * 
   * Future implementation will:
   * 1. Get report metadata from experiment details (via BFF)
   * 2. Request presigned S3 URL from BFF
   * 3. Download report from S3
   * 
   * @param experimentId Experiment ID
   * @returns Observable with report download URL
   */
  getReportDownloadUrl(experimentId: string): Observable<string | null> {
    // Stub implementation
    console.warn('Report retrieval not yet implemented. Reports are generated by Lambda.');
    return of(null);
  }
}
