"""
Handler for ReportGenerated events.
Sends notifications when a report is generated by the reporting-service Lambda.
"""
import json
import logging
from typing import Dict, Any

from services.recipient_service import RecipientService
from services.email_service import EmailService
from services.webhook_service import WebhookService

logger = logging.getLogger(__name__)


def handle_report_generated(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    Handle ReportGenerated event from EventBridge.

    Event envelope structure (turaf standard, published by reporting-service):
        {
            "id": "event-uuid",
            "detail-type": "ReportGenerated",
            "detail": {
                "organizationId": "org-id",
                "payload": {
                    "reportId": "rpt-id",
                    "experimentId": "exp-id",
                    "reportLocation": "s3://bucket/path/report.pdf",
                    "reportFormat": "PDF",
                    "generatedAt": "ISO-8601"
                }
            }
        }

    Pipeline:
        1. Extract report and organization details from event envelope
        2. Resolve notification recipients via RecipientService
        3. Send email with report link to each recipient via EmailService
        4. Deliver webhooks via WebhookService

    Args:
        event: EventBridge event containing report generation details
        context: Lambda context object

    Returns:
        Dict with statusCode and body
    """
    try:
        # Extract from standard event envelope
        detail = event.get('detail', {})
        payload = detail.get('payload', {})
        event_id = event.get('id')

        organization_id = detail.get('organizationId')
        report_id = payload.get('reportId')
        experiment_id = payload.get('experimentId')
        report_location = payload.get('reportLocation')

        # Validate required fields
        if not report_id:
            raise ValueError('Missing reportId in event detail.payload')
        if not experiment_id:
            raise ValueError('Missing experimentId in event detail.payload')
        if not organization_id:
            raise ValueError('Missing organizationId in event detail')

        logger.info(
            'Processing ReportGenerated event',
            extra={
                'report_id': report_id,
                'experiment_id': experiment_id,
                'organization_id': organization_id,
                'event_id': event_id
            }
        )

        # Build normalized report data for templates
        report_data = {
            'reportId': report_id,
            'experimentId': experiment_id,
            'experimentName': payload.get('experimentName', f'Experiment {experiment_id}'),
            'organizationId': organization_id,
            'reportUrl': report_location,
            'reportFormat': payload.get('reportFormat', 'PDF'),
            'generatedAt': payload.get('generatedAt'),
        }

        email_count = 0
        email_errors = 0
        webhook_count = 0

        # Resolve recipients and send email notifications
        recipient_service = RecipientService()
        try:
            recipients = recipient_service.get_recipients(
                organization_id, 'report.generated', channel='email'
            )

            email_service = EmailService()
            for recipient_email in recipients:
                try:
                    email_service.send_report_generated_email(
                        recipient_email, report_data
                    )
                    email_count += 1
                except Exception as e:
                    email_errors += 1
                    logger.error(
                        'Failed to send report generated email',
                        extra={
                            'recipient': recipient_email,
                            'report_id': report_id,
                            'error': str(e)
                        },
                        exc_info=True
                    )
        finally:
            recipient_service.close()

        # Deliver webhook notifications
        webhook_service = WebhookService()
        try:
            webhook_results = webhook_service.send_webhooks(
                organization_id=organization_id,
                event_type='report.generated',
                event_id=event_id,
                event_data=report_data
            )
            webhook_count = sum(1 for r in webhook_results if r.success)
        finally:
            webhook_service.close()

        logger.info(
            'ReportGenerated notification processing complete',
            extra={
                'report_id': report_id,
                'experiment_id': experiment_id,
                'emails_sent': email_count,
                'email_errors': email_errors,
                'webhooks_delivered': webhook_count
            }
        )

        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'ReportGenerated notification processed successfully',
                'reportId': report_id,
                'experimentId': experiment_id,
                'emailsSent': email_count,
                'webhooksDelivered': webhook_count
            })
        }

    except ValueError as e:
        logger.error(
            'Validation error in ReportGenerated handler',
            extra={'error': str(e)},
            exc_info=True
        )
        return {
            'statusCode': 400,
            'body': json.dumps({'error': f'Validation error: {str(e)}'})
        }
    except Exception as e:
        logger.error(
            'Error processing ReportGenerated event',
            extra={'error': str(e), 'error_type': type(e).__name__},
            exc_info=True
        )
        raise
